spring.application.name=quiethelp

# Configuracion de Supabase (para validar tokens)
app.supabase.url=https://losnmfekwxbvcaldnzij.supabase.co
app.supabase.api-key=sb_publishable_TPYtlAj_ZgLdCwUyzcmdqw_vM_EgQ94

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.losnmfekwxbvcaldnzij
spring.datasource.password=QuietHelpBBDD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Limite estricto de conexiones
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000

#Conexion N8N WebHook
n8n.webhook.url=http://localhost:5678/webhook-test/5bf2f073-5574-406d-bb79-8eaf2c82a082